[package]
authors = ["Garrett Berg <vitiral@gmail.com>"]
name = "test-pass"
version = "0.1.0"
build = "build.rs"

[build-dependencies]

[build-dependencies.build_static]
optional = false
path = "../.."
